
FROM python:3.12.3-slim

WORKDIR /app/lucit_ubdcc/lucit-ubdcc-mgmt

RUN mkdir -vp /app/lucit_ubdcc
COPY ./container/lucit-ubdcc-mgmt/ /app/lucit_ubdcc/lucit-ubdcc-mgmt

RUN pip install -r requirements.txt

CMD ["python", "start_ubdcc_mgmt.py"]
