apiVersion: v1
entries:
  lucit-ubdcc:
  - apiVersion: v2
    appVersion: 0.1.4
    created: "2024-10-28T15:33:28.911485652+01:00"
    description: 'Manage multiple and redundant UNICORN Binance Local Depth Cache
      Instances for high-frequency access to Binance''s  DepthCache data (order books). '
    digest: 9382d0002c5f0cddb7a5e392fbe0b9c0d4c6500d88fb7af5966caf754cdb60bd
    name: lucit-ubdcc
    type: application
    urls:
    - https://unicorn-depthcache-cluster-for-binance.docs.lucit.tech/helm/lucit-ubdcc-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    appVersion: 0.1.3
    created: "2024-10-28T15:33:28.910417513+01:00"
    description: 'Manage multiple and redundant UNICORN Binance Local Depth Cache
      Instances for high-frequency access to Binance''s  DepthCache data (order books). '
    digest: f579313dadfca55851b2ec464e194d4032e06637dfe9f5223d9798ddaf91ccdf
    name: lucit-ubdcc
    type: application
    urls:
    - https://unicorn-depthcache-cluster-for-binance.docs.lucit.tech/helm/lucit-ubdcc-0.1.3.tgz
    version: 0.1.3
generated: "2024-10-28T15:33:28.909378851+01:00"
