[tool.poetry]
name = "lucit-ubdcc-mgmt"
version = "0.1.4"
description = "LUCIT UBDCC Mgmt Service"
authors = ["LUCIT Systems and Development <info@lucit.tech>"]
license = "LSOSL - LUCIT Synergetic Open Source License"
readme = "README.md"
homepage = "https://www.lucit.tech/unicorn-depthcache-cluster-for-binance.html"
documentation = "https://www.lucit.tech/unicorn-depthcache-cluster-for-binance.html"
repository = "https://github.com/LUCIT-Systems-and-Development/unicorn-depthcache-cluster-for-binance"

[tool.poetry.urls]
'Howto' = 'https://www.lucit.tech/unicorn-depthcache-cluster-for-binance.html#howto'
'Documentation' = 'https://unicorn-depthcache-cluster-for-binance.docs.lucit.tech'
'Wiki' = 'https://github.com/LUCIT-Systems-and-Development/unicorn-depthcache-cluster-for-binance/wiki'
'Author' = 'https://www.lucit.tech'
'Changes' = 'https://github.com/LUCIT-Systems-and-Development/unicorn-depthcache-cluster-for-binance/blob/master/packages/lucit-ubdcc-mgmt/CHANGELOG.md'
'License' = 'https://github.com/LUCIT-Systems-and-Development/unicorn-depthcache-cluster-for-binance/blob/master/LICENSE'
'Issue Tracker' = 'https://github.com/LUCIT-Systems-and-Development/unicorn-depthcache-cluster-for-binance/issues'
'Telegram' = 'https://t.me/unicorndevs'
'Chat' = 'https://app.gitter.im/#/room/#unicorn-depthcache-cluster-for-binance:gitter.im'
'Get Support' = 'https://www.lucit.tech/get-support.html'
'LUCIT Online Shop' = 'https://shop.lucit.services/software/unicorn-depthcache-cluster-for-binance'

[tool.poetry.dependencies]
python = ">=3.12.0"
lucit-licensing-python = ">=1.8.2"
lucit-ubdcc-shared-modules = "==0.1.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["setuptools", "wheel", "Cython", "pip"]
build-backend = "setuptools.build_meta"

[tool.poetry.package_data]
"lucit_ubdcc_mgmt" = ["*.so", "*.dll", "*.pyd"]
